// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.versions = [
            "kotlin"    : '2.2.0',
            "navigation": '2.9.0',
            "hilt"      : '2.56.2',
            "room"      : "2.7.2",
            "paging"    : "2.6.1"
    ]

    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${versions.kotlin}"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:${versions.navigation}"
        classpath "com.google.dagger:hilt-android-gradle-plugin:${versions.hilt}"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

plugins {
    id "com.cookpad.android.plugin.license-tools" version "1.2.8"
    id 'com.google.devtools.ksp' version '2.2.0-2.0.2' apply false
}

allprojects {
    repositories {
        mavenCentral()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
